---
name: TestSBOM

on:
  pull_request:
    branches: [master]
    paths:
      - ".github/workflows/testsbom.yml"
      - "cyclonedx-lib/**"

# Cancel existing runs if user makes another push.
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test_sbom_gen:
    name: gen_sbom
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/centos7_build_image 
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

    # Build with jdk8 to ensure TemurinGenSBOM meets min compatibility
    - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
      id: setup-java
      with:
        java-version: 8
        distribution: 'temurin'

    - name: Build TemurinGenSBOM.java
      run: |
        ant -noinput -buildfile cyclonedx-lib/build.xml clean
        ant -noinput -buildfile cyclonedx-lib/build.xml build

    - name: Run TemurinGenSBOM Unit test
      run: |
        ant -noinput -buildfile cyclonedx-lib/build.xml run

    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      name: Collect and Archive TemurinGenSBOM Artifacts
      with:
        name: testSBOM 
        path: cyclonedx-lib/build/testSBOM.json

